# Generated by Django 2.2.3 on 2019-10-29 18:43

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_en',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Títle'),
            preserve_default=False,
        ),
    ]
