version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    #command: gunicorn utilscrw.wsgi -b 0.0.0.0:8000
    environment:
      - SECRET_KEY=########
      - DEBUG=1
      - RPC_USER=########
      - RPC_PHRASE=########
      - RPC_URL=########
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: