# Generated by Django 2.2.3 on 2019-10-29 18:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content_en',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Títle'),
            preserve_default=False,
        ),
    ]
