# Generated by Django 2.2.2 on 2019-07-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faucet', '0004_auto_20190701_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faucet',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
