# Generated by Django 2.2.2 on 2019-06-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190630_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addr_withdraw',
        ),
    ]
