# Generated by Django 2.2.2 on 2019-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_profile_addr_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance_faucet',
            field=models.FloatField(default=0),
        ),
    ]
